# Generated by Django 3.0.4 on 2020-11-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSummary',
            fields=[
                ('car_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('run_start_date', models.DateTimeField()),
                ('result', models.CharField(max_length=20)),
                ('block_no', models.BigIntegerField(blank=True, null=True)),
                ('evaluation_place', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('offpoint_category', models.CharField(blank=True, max_length=100, null=True)),
                ('offpoint', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ana_summary',
                'managed': False,
            },
        ),
    ]
