# Generated by Django 3.0.4 on 2020-11-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipMeasurementTbl',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('equip_id', models.BigIntegerField()),
                ('device_id', models.BigIntegerField()),
                ('seqno', models.BigIntegerField()),
                ('measurement_date', models.DateTimeField()),
                ('run_start_date', models.DateTimeField()),
                ('run_stop_date', models.DateTimeField()),
                ('record_start_date', models.DateTimeField()),
                ('record_stop_date', models.DateTimeField()),
                ('type_id', models.BigIntegerField()),
                ('data_val', models.CharField(max_length=255)),
                ('reg_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'equip_measurement_tbl',
                'managed': False,
            },
        ),
    ]
