# Generated by Django 3.0.4 on 2020-11-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmeasurementtbl',
            options={'get_latest_by': ['reg_date'], 'managed': False},
        ),
    ]
