# Generated by Django 3.0.4 on 2020-11-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_id', models.BigIntegerField(blank=True, null=True)),
                ('average', models.BigIntegerField(blank=True, null=True)),
                ('deviation', models.BigIntegerField(blank=True, null=True)),
                ('rank_office', models.BigIntegerField(blank=True, null=True)),
                ('num_office', models.BigIntegerField(blank=True, null=True)),
                ('rank_area', models.BigIntegerField(blank=True, null=True)),
                ('num_area', models.BigIntegerField(blank=True, null=True)),
                ('office_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('point', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_start_date', models.TimeField(blank=True, null=True)),
                ('total_score', models.CharField(blank=True, max_length=20, null=True)),
                ('shin_score', models.CharField(blank=True, max_length=20, null=True)),
                ('gi_score', models.CharField(blank=True, max_length=20, null=True)),
                ('tai_score', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.TimeField(blank=True, null=True)),
                ('car_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_id', models.BigIntegerField(blank=True, null=True)),
                ('training_category', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('training_menu', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'training',
                'managed': False,
            },
        ),
    ]
