# Generated by Django 3.0.4 on 2020-11-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_id', models.BigIntegerField(blank=True, null=True)),
                ('summary_category_id', models.BigIntegerField(blank=True, null=True)),
                ('score_category', models.BigIntegerField(blank=True, null=True)),
                ('point', models.BigIntegerField(blank=True, null=True)),
                ('point_rank', models.CharField(blank=True, max_length=20, null=True)),
                ('average', models.BigIntegerField(blank=True, null=True)),
                ('deviation', models.BigIntegerField(blank=True, null=True)),
                ('rank_office', models.BigIntegerField(blank=True, null=True)),
                ('num_office', models.BigIntegerField(blank=True, null=True)),
                ('rank_area', models.BigIntegerField(blank=True, null=True)),
                ('num_area', models.BigIntegerField(blank=True, null=True)),
                ('office_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'score1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Summary1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.BigIntegerField(blank=True, null=True)),
                ('run_start_date', models.TimeField(blank=True, null=True)),
                ('total_score', models.CharField(blank=True, max_length=20, null=True)),
                ('total_score_rank', models.CharField(blank=True, max_length=20, null=True)),
                ('mental_score', models.CharField(blank=True, max_length=20, null=True)),
                ('tech_score', models.CharField(blank=True, max_length=20, null=True)),
                ('physical_score', models.CharField(blank=True, max_length=20, null=True)),
                ('total_comment', models.TextField(blank=True, null=True)),
                ('mental_comment', models.TextField(blank=True, null=True)),
                ('mental_required_training_comment', models.TextField(blank=True, null=True)),
                ('mental_training_comment', models.TextField(blank=True, null=True)),
                ('tech_comment', models.TextField(blank=True, null=True)),
                ('tech_required_training_comment', models.TextField(blank=True, null=True)),
                ('tech_training_comment', models.TextField(blank=True, null=True)),
                ('physical_comment', models.TextField(blank=True, null=True)),
                ('physical_required_training_comment', models.TextField(blank=True, null=True)),
                ('physical_training_comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'summary1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Training1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_id', models.BigIntegerField(blank=True, null=True)),
                ('training_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training1',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
